hucovaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('hucovaria/admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns.append(path('hucovaria/', include('main.urls')))

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('datasets/', views.datasets, name='datasets'),
	path('tmp/', views.makeQuery, name='query'),
	path('help/', views.help, name='help'),
	path('results/<str:result_id>/table/', views.TableView.as_view(), name='table'),
	path('results/<str:result_id>/network/', views.network, name='network'),
]

#urlpatterns = []

main/models.py
from django.db import models


class Result(models.Model):
    id = models.CharField(max_length=60, primary_key=True)
    time = models.DateTimeField()
    annotation = models.CharField(max_length=60)

    def __str__(self):
        return self.id

class Gene(models.Model):
	symbol = models.CharField(max_length=60, primary_key=True)
	organism = models.CharField(max_length=60)

class Interaction(models.Model):
	virus = models.CharField(max_length=60)
	host = models.CharField(max_length=60)
	interaction = models.CharField(max_length=60)
	strain = models.CharField(max_length=60)
	localization = models.CharField(max_length=60)
	tissue_expression = models.CharField(max_length=60)

	def __str__(self):
		return str(self.virus) + "_" + str(self.host) + "_" + str(self.strain) + "_" + str(self.id)

class KEGG(models.Model):
	gene = models.ForeignKey(Gene, on_delete=models.CASCADE)
	name = models.CharField(max_length=60)
	description = models.CharField(max_length=100)

class GO(models.Model):
	gene = models.ForeignKey(Gene, on_delete=models.CASCADE)
	name = models.CharField(max_length=60)
	description = models.CharField(max_length=100)
	type = models.CharField(max_length=10)

class InteractionResult(models.Model):
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

class VirusResult(models.Model):
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

class HostResult(models.Model):
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

class TissueExpressionResult(models.Model):
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

class GeneOntologyResult(models.Model):
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

class KeggResult(models.Model):
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

class LocalizationResult(models.Model):
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

class StrainResult(models.Model):
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	content = models.CharField(max_length=100)

	def __str__(self):
		return self.content

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from uuid import uuid4
from django.core.mail import send_mail
from django.conf import settings
import os
import pandas as pd
import mimetypes

from .models import *

def home(request):
	context = {
		'title': 'Home',
		'virusProteins': ['S', 'E', 'M', 'N', 'nsp1', 'nsp2', 'nsp3', 'nsp4', 'nsp5',
						'nsp6', 'nsp7', 'nsp8', 'nsp9', 'nsp10', 'nsp11', 'nsp12', 'nsp13',
						'nsp14', 'nsp15', 'nsp16', 'ORF3a', 'ORF3d', 'ORF6', 'ORF7a',
						'ORF7b', 'ORF8', 'ORF9b', 'ORF9c', 'ORF10'],
		'strains': [
					{'name': 'B.1.1.7', 'label': 'Alpha'},
					{'name': 'B.1.351', 'label': 'Beta'},
					{'name': 'B.1.427', 'label': 'Epsilon'},
					{'name': 'B.1.525', 'label': 'Eta'},
					{'name': 'B.1.526', 'label': 'Iota'},
					{'name': 'B.1.617', 'label': 'Kappa'},
					{'name': 'B.1.617.2', 'label': 'Delta'},
					{'name': 'B.1.617.3', 'label': 'N/A'},
					{'name': 'B.1.621', 'label': 'Mu'},
					{'name': 'P.1', 'label': 'Gamma'},
					{'name': 'P.2', 'label': 'Zeta'},
					{'name': 'Reference', 'label': 'Wuhan'},
					],
		'annotations': [{'name': 'tissue_expression', 'pprint': 'Tissue Expression'}, {'name': 'localization', 'pprint': 'Localization'}, {'name': 'KEGG', 'pprint': 'KEGG'}],
		'ontologies': ['MF', 'BP', 'CC'],
		'result_name': str(uuid4())[:18],
	}
	checkResults()
	return render(request, 'home.html', context)

def about(request):
	context = {
		'title': 'About',
	}
	return render(request, 'about.html', context)

def help(request):
    context = {
        'title': 'Help',
    }
    return render(request, 'help.html', context)

def datasets(request):
	context = {
		'title': 'Datasets',
	}
	return render(request, 'datasets.html', context)

def getInteractionQuerySet(result_id):
	result = Result.objects.get(pk=result_id)
	virus_l = [v.content for v in result.virusresult_set.all()]
	host_l = [h.content for h in result.hostresult_set.all()]
	strains = [s.content for s in result.strainresult_set.all()]
	interactionType = result.interactionresult_set.first()

	qs = Interaction.objects.filter(virus__in=virus_l).filter(host__in=host_l).filter(strain__in=strains)

	return qs

def makeQuery(request):
    strains = ['B.1.1.7',
	    'B.1.351',
	    'B.1.427',
	    'B.1.525',
	    'B.1.526',
	    'B.1.617',
		'B.1.617.2',
		'B.1.617.3',
		'B.1.621',
		'P.1',
		'P.2',
		'Reference']

	#add to Result
    annotation = request.POST.get('Annotation')

    newID = request.POST.get('result_name')
    filename=f'media/{newID}.csv'

    newResult = Result(id=newID, time=timezone.now(), annotation=annotation)
    newResult.save()

	#add StrainResults
    strains_to_filter = []
    for strain in strains:
        if request.POST.get(strain):
            newStrainResult = StrainResult(result=newResult, content=strain)
            newStrainResult.save()

	#add HostResults
    for h in request.POST.get('human_prots_text').split(','):
        host_gene = h.strip()
        newHostResult = HostResult(result=newResult, content=host_gene)
        newHostResult.save()

	#add VirusResults
    for v in request.POST.get('hidden_sars_prots').split(','):
        newVirusResult = VirusResult(result=newResult, content=v)
        newVirusResult.save()

	#add InteractionResults
    interactionType = request.POST.get('interaction')
    if interactionType == 'Interolog':
        newInteractionResult = InteractionResult(result=newResult, content=interactionType)
        newInteractionResult.save()
    elif interactionType == 'Domain':
        newInteractionResult = InteractionResult(result=newResult, content=interactionType)
        newInteractionResult.save()

    Interaction_qs = getInteractionQuerySet(newResult.id)
    df = pd.DataFrame(Interaction_qs.values())
    df.to_csv(filename, index=None)
    newResult.save()

    #send email if given

    if request.POST.get('email'):
        send_mail(
            f'HuCoVaria results for {newID}',
            f'Thank you for using HuCoVaria! Here is the link to your results: {request.POST.get("link")}',
            settings.EMAIL_HOST_USER,
            [request.POST.get('email')],
        )

    return HttpResponseRedirect(reverse('main:home'))

def checkResults():
    for result in Result.objects.all():
        diff = timezone.now() - result.time
        if diff.days > 7:
            file_path = f'/media/{result.id}.csv'
            os.remove(f'./media/{result.id}.csv')
            result.delete()

class TableView(generic.ListView):
	template_name = 'table.html'
	context_object_name = 'query'

	def get_queryset(self):
		result_id = self.request.META['PATH_INFO'].split('/')[3]
		annotation = Result.objects.get(pk=result_id).annotation
		qs = getInteractionQuerySet(result_id)
		qs_l = qs.values()
		new = []
		if annotation == 'Gene Ontology':
			for row in qs_l:
				go = GO.objects.filter(gene=row['host'])
				if len(go) != 0:
					for g in go:
						newrow = row.copy()
						newrow['GO'] = g.name
						newrow['GO_Description'] = g.description
						newrow['GO_Type'] = g.type
						new.append(newrow)
				else:
					newrow = row.copy()
					new.append(newrow)
			return new
		elif annotation == 'KEGG':
			for row in qs_l:
				kegg = KEGG.objects.filter(gene=row['host'])
				if len(kegg) != 0:
					for k in kegg:
						newrow = row.copy()
						newrow['KEGG'] = k.name
						newrow['KEGG_Description'] = k.description
						new.append(newrow)
				else:
					newrow = row.copy()
					new.append(newrow)
			return new

		return qs_l

	def get_context_data(self, **kwargs):
		result_id = self.request.META['PATH_INFO'].split('/')[3]
		context = super().get_context_data(**kwargs)
		annotation = Result.objects.get(pk=result_id).annotation
		context['annotation'] = {'annotation': annotation}
		if annotation == 'KEGG':
		    context['annotation']['pprint'] = 'KEGG'
		elif annotation == 'Gene Ontology':
		    context['annotation']['pprint'] = 'Gene Ontology'
		elif annotation == 'localization':
		    context['annotation']['pprint'] = 'Localization'
		elif annotation == 'tissue_expression':
		    context['annotation']['pprint'] = 'Tissue Expression'
		context['title'] = f'Table View - {Result.objects.get(pk=result_id).id}'
		context['subtitle'] = Result.objects.get(pk=result_id).id
		context['result_id'] = result_id
		return context

def network(request, result_id):
    context = {}

    df = pd.read_csv(f'media/{result_id}.csv')
    cols = ['id', 'color']
    virus = df[['virus']].drop_duplicates()
    virus['color'] = ['red' for x in range(len(virus))]
    host = df[['host']].drop_duplicates()
    host['color'] = ['blue' for x in range(len(host))]
    virus.columns=cols
    host.columns=cols
    nodes = pd.concat([virus, host])

    strain_color = {
        'B.1.1.7': '#FF33EE',
        'B.1.351': '#A033FF',
        'B.1.427': '#33C2FF',
        'B.1.525': '#33FFA7',
        'B.1.526': '#33FF41',
        'B.1.617': '#FFF933',
        'B.1.617.2': '#FFA933',
        'B.1.617.3': '#FF7833',
        'B.1.621': '#000000',
        'P.1': '#806C23',
        'P.2': '#A30D5C',
        'Reference': '#0D85A3'
    }
    strain_colors = []

    for k,v in strain_color.items():
        strain_colors.append({'name': k, 'color': v})

    interactions = []
    for index,row in df.iterrows():
        virus = row['virus']
        host = row['host']
        interactions.append({'id': virus + "_" + host + "_" + strain_color[row['strain']], 'source': virus, 'target': host, 'color': strain_color[row['strain']], 'strain': row['strain']})

    context['result_id'] = result_id
    context['interaction_count'] = len(df[['virus', 'host']].drop_duplicates())
    context['virus_count'] = len(set(df.virus.to_list()))
    context['host_count'] = len(set(df.host.to_list()))
    context['strain_colors'] = strain_colors
    context['nodes'] = nodes.to_dict('records')
    context['interactions'] = interactions
    context['title'] = f'Network View - {Result.objects.get(pk=result_id).id}'
    context['subtitle'] = Result.objects.get(pk=result_id).id

    return render(request, 'network.html', context)

main/templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>{{ title }}</h1>
	<div class="container">
		<p>SARS-CoV-2, a betacoronavirus, and the pathogen that causes COVID-19, has impacted the world in a variety of ways. Vaccines and other treatments have helped prevent and treat COVID-19. However, as with all viruses, SARS-CoV-2 will mutate, possibly resulting changes in transmissibility and different pathways the virus can be involved in. Investigating the protein-protein interactions between human proteins and various strains of SARS-CoV-2 proteins can give insight into common pathways the various strains are involved in.</p>
		<p>The interactions are classified into two different groups based on the method of being predicted: interolog (using BLAST) and domain (using HMMER). This resulted in 178,713 interactions across 12 strains (including the original, reference). These interactions were also characterized with KEGG (pathway enrichment), Gene Ontology (GO, functional enrichment), Subcellular Localization and Tissue Expression.</p>
		<p>E-mail hucovaria@gmail.com for any problems, issues or questions that arise from using this webtool.</p>
	</div>
{% endblock content %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- cytoscape js -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.20.0/cytoscape.min.js"></script>

    <!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- data tables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.12.0/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/datatables.min.css"/>
     
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.12.0/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/datatables.min.js"></script>

	<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/cytoscape.js-navigator.css' %}">
	<link rel="shortcut icon" href="{% static 'main/favicon.ico' %}"/>

	{% if title %}
		<title>HuCoVarIA {{ title }}</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
  		<nav class="navbar navbar-expand navbar-dark bg-steel fixed-top">
    		<div class="container">
      			<a class="navbar-brand mr-4" href="{% url 'main:home' %}">HuCoVarIA</a>
      			<div class="collapse navbar-collapse" id="navbarToggle">
        			<div class="navbar-nav mr-auto">
          				<a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
          				<a class="nav-item nav-link" href="{% url 'main:about' %}">About</a>
						<a class="nav-item nav-link" href="{% url 'main:datasets' %}">Datasets</a>
						<a class="nav-item nav-link" href="{% url 'main:help' %}">Help</a>
        			</div>
        	    </div>
        	    <div class="navbar-brand">Human/COVID-19 Variants Interactions</div>
    		</div>
  		</nav>
	</header>
    <main role="main" class="container">
    	<div class="row">
    		<div class="col-12">
    			{% block content %}{% endblock %}
    		</div>
    	</div>
    </main>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

main/templates/datasets.html
{% extends "base.html" %}

{% block content %}
<h1>{{ title }}</h1>
	<div class="container">
		<ul>
			<li><h5><a href="https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.39/" target="_blank" rel="noopener noreferrer">Human Genome</a></h5></li>
			<li><h5><a href="https://www.ncbi.nlm.nih.gov/nuccore/NC_045512.2/" target="_blank" rel="noopener noreferrer">SARS-CoV-2 Reference Genome</a></h5></li>
			<li><h5>SARS-CoV-2 Variants' Genomes from NCBI:</h5>
				<ul>
					<li><h6><a href="https://www.ncbi.nlm.nih.gov/nuccore/LR991699.2/" target="_blank" rel="noopener noreferrer">B.1.1.7 (LR991699.2)</a></h6></li>
				</ul>
				<h5>From <span data-toggle="tooltip" data-placement="top" title="Account required for access to files"><a href="https://www.gisaid.org/" target="_blank" rel="noopener noreferrer">GISAID Initiative</a></span>:</h5>
				<ul>
					<li><h6>B.1.351 (EPI_ISL_712081)</h6></li>
					<li><h6>B.1.427 (EPI_ISL_468365)</h6></li>
					<li><h6>B.1.525 (EPI_ISL_4255014)</h6></li>
					<li><h6>B.1.526 (EPI_ISL_3364539)</h6></li>
					<li><h6>B.1.617 (EPI_ISL_1360376)</h6></li>
					<li><h6>B.1.617.2 (EPI_ISL_2461258)</h6></li>
					<li><h6>B.1.617.3 (EPI_ISL_2556860)</h6></li>
					<li><h6>B.1.621 (EPI_ISL_4077325)</h6></li>
					<li><h6>P.1 (EPI_ISL_833137)</h6></li>
					<li><h6>P.2 (EPI_ISL_2157561)</h6></li>
				</ul>
			</li>


			<li><h5>Tissue Expression: <a href="https://storage.googleapis.com/gtex_analysis_v8/rna_seq_data/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.gz" target="_blank" rel="noopener noreferrer">Dataset</a>|<a href="https://gtexportal.org/home/" target="_blank" rel="noopener noreferrer">Website</a></h5></li>
			<li><h5>Subcellular Localization: <a href="https://www.proteinatlas.org/download/subcellular_location.tsv.zip" target="_blank" rel="noopener noreferrer">Dataset</a>|<a href="https://www.proteinatlas.org/">Website</a></h5></li>
		</ul>

	<h2>Databases</h2>
		<ul>
			<li><h5><a href="https://www.genome.jp/kegg/pathway.html" target="_blank" rel="noopener noreferrer">KEGG Pathway</a></h5></li>
			<li><h5><a href="http://geneontology.org/" target="_blank" rel="noopener noreferrer">Gene Ontology</a></h5></li>
		</ul>

	</div>
{% endblock content %}

main/templates/help.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ title }}</h1>
	<div class="container">
        <h4>Home Page: Making a Query</h4>
        Queries are performed from the 'Home' page which looks like: <p><img src="{% static 'main/hucovaria_home.PNG' %}" class="med-img"></p>
        <ol>
            <li>Enter your human proteins. These values must be comma separated. Gene symbols are supported only. Type directly into the box or upload a file with your comma-separated proteins.
                <p><img src="{% static 'main/hucovaria_home_human_proteins_upload.PNG' %}" class="small-img"></p></li>
            <li>Select which strains of SARS-CoV-2 to be included in your query. More information on strains can be found at: <a href="https://cov-lineages.org/">Pango Lineages</a>.
                <p><img src="{% static 'main/hucovaria_home_strains.PNG' %}" class="small-img"></p></li>
            <li>Select which SARS-CoV-2 proteins to be included in your predicted interactions.
                <p><img src="{% static 'main/hucovaria_home_covid_proteins.PNG' %}" class="small-img"></p></li>
            <li>Select which annotation type to be included. More information on each annotation type can be found here:
                <ul>
                    <li><a href="https://gtexportal.org/home/" target="_blank" rel="noopener noreferrer">Tissue Expression</a></li>
                    <li><a href="https://www.proteinatlas.org/">Subcellular Localization</a></li>
                    <li><a href="https://www.genome.jp/kegg/pathway.html" target="_blank" rel="noopener noreferrer">KEGG Pathway</a></li>
                    <li><a href="http://geneontology.org/" target="_blank" rel="noopener noreferrer">Gene Ontology</a></li>
                </ul>
                <p><img src="{% static 'main/hucovaria_home_annotations.PNG' %}" class="small-img"></p>
            </li>
            <li>Select which interaction type:
            <p>Interolog interactions are based off the interolog approach, involving <a href="https://blast.ncbi.nlm.nih.gov/Blast.cgi" target="_blank" rel="noopener noreferrer">NCBI's BLAST</a>, to predicting Host-Pathogen Interactions (HPIs). The interolog databases used can be found at the <a href="{% url 'main:datasets' %}">'Datasets'</a> tab.</p>
            <p>Domain interactions involve predicting HPIs via the interactions between specific domains, or subunits of proteins. This approach utilizes <a href="http://hmmer.org/" target="_blank" rel="noopener noreferrer">HMMER</a>, and several domain-domain interaction databases, also found under the <a href="{% url 'main:datasets' %}">'Datasets'</a> tab.</p>
            <p>Combined interactions include both interolog and domain interactions.</p>
            </li>
            <li>Click the 'Submit Query' to send in your query. A pop-up window will be displayed and have a link to the table view of your results and an indicator representing the progress of your query.
                <p><img src="{% static 'main/hucovaria_home_submit.PNG' %}" class="small-img"><img src="{% static 'main/hucovaria_home_modal.PNG' %}" class="small-img"></p></li>
        </ol>        
	</div>

	<div class="container">
        <h4>Table View</h4>
        <p>The table view displays all of the interaction information in a paginated-table format. Viral gene, host gene, strain, interaction type and annotation information are all displayed in the table. There are two buttons to download the table: one in an excel format and the other in a csv format. There is also a search bar to narrow down entries. Here is a typical table view:</p>
        <p><img src="{% static 'main/hucovaria_table.PNG' %}" class="med-img"></p>
        <p>Click the 'To Network View' to display the original interaction information in a network view.</p>
	</div>

	<div class="container">
	    <h4>Network View</h4>
        <p>The network view displays the interaction information as a network utilizing <a href="https://js.cytoscape.org/" target="_blank" rel="noopener noreferrer">Cytoscape.js</a> to create the network. Only the viral and host proteins and SARS-CoV-2 strains are displayed. The proteins are displayed as nodes whereas the strains are displayed as edges. A legend is provided and edges and nodes can be removed as well. Right clicking and holding on a node gives options to access more information about that protein. Here is a typical network view: </p>
        <p><img src="{% static 'main/hucovaria_network.PNG' %}" class="med-img"></p>
        <p>Here is a snapshot of the menu provided when right-clicking and holding on a node:</p>
        <p><img src="{% static 'main/hucovaria_network_menu.PNG' %}" class="small-img"></p>
	</div>
{% endblock content %}

main/templates/results.html
{% extends "base.html" %}

{% block content %}
	<h1>{{ title }}</h1>
	<hr>

<div class="container">
    {% for result in results %}
        <div class="card">
        	<div class="card-body">
        		<h5 class="card-title">{{ result.name }}</h5>
        		<h6 class="card-subtitle mb-2 text-muted">{{ result.id }}</h6>
        		<p class="sub-text"><a href="{% url 'main:table' result.id %}">Table View</a>|<a href="{%url 'main:network' result.id %}">Network View</a></p>
        	</div>
        </div>
    {% empty %}
        <div class="container">
            <h5>Sorry, no results at this time. Check back in a little if you recently submitted a query or return to the home tab to submit a query</h5>
        </div>
    {% endfor %}
</div>

{% endblock content %}

main/templates/table.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ title }} | <a class="btn btn-primary" href="{% url 'main:network' result_id %}">To Network View</a></h1>
<hr>

<div id="loading">
    <i class="fa fa-spinner large center"></i>
</div>

<div class="container">
	<div id="table-wrapper" hidden>
		<table class="display" id="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">V Gene</th>
					<th scope="col">H Gene</th>
					<th scope="col">Strain</th>
					<th scope="col">Interaction Type</th>
					<th scope="col">{{ annotation.pprint }}</th>
					{% if annotation.annotation == "Gene Ontology" %}
					<th scope="col">Ontology Type</th>
					<th scope="col">Ontology Description</th>
					{% elif annotation.annotation == "KEGG" %}
					<th scope="col">Pathway Description</th>
					{% endif %}
				</tr>
			</thead>
			<tbody id="table-body">
				{% for line in query %}
						<tr>
						<th scope="row">{{ forloop.counter }}</th>
						<td>{{ line.virus }}</td>
						<td><a href="https://www.ncbi.nlm.nih.gov/search/all/?term={{ line.host }}" target="_blank" rel="noopener noreferrer">{{ line.host }}</a></td>
						<td>{{ line.strain }}</td>
						<td>{{ line.interaction }}</td>
					{% if annotation.annotation == "KEGG" %}
						<td><a href="https://www.genome.jp/pathway/{{ line.KEGG }}" target="_blank" rel="noopener noreferrer">{{ line.KEGG }}</a></td>
						<td>{{ line.KEGG_Description }}</td>
					{% elif annotation.annotation == "Gene Ontology" %}
						<td><a href="http://amigo.geneontology.org/amigo/term/{{line.GO}}" target="_blank" rel="noopener noreferrer">{{ line.GO }}</a></td>
						<td>{{ line.GO_Type }}</td>
						<td>{{ line.GO_Description }}</td>
					{% elif annotation.annotation == "localization" %}
						<td>{{ line.localization }}</td>
					{% elif annotation.annotation == "tissue_expression" %}
						<td><a href="https://gtexportal.org/home/gene/{{ line.host }}" target="_blank" rel="noopener noreferrer">{{ line.tissue_expression }}</a></td>
					{% endif %}
				</tr>
				{% endfor %}
				
			</tbody>
		</table>
	</div>
</div>

<script>

var table = $("#table").DataTable({
    dom: "Bfrtip",
    buttons: ["excel", "csv"]
});

document.getElementById("loading").hidden = true;
document.getElementById("table-wrapper").hidden = false;

</script>

{% endblock content %}